config/routes.rb
Rails.application.routes.draw do


  # devise_for :customers
  # devise_for :admins

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# devise_for :admin, controllers: {
#   sessions: "admin/sessions"
# }
  # devise_for :customers
  namespace :admin do
    get 'order_products/updete'
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new'
     resources :items
    root to: 'homes#top'
    get 'homes/top'
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    resources :shipping_addresses

    resources :items, only: [:index, :show]

    resource :customers, except:[:create] do
    collection do
    get 'quit'
    patch 'out'
    end
    end
  end
    devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
    sessions: 'public/sessions'
}
  scope module: :public do
  resources :cart_items do
    collection do
    delete 'destroy_all'
    end
  end
  end
  scope module: :public do
  resources :orders do
    collection do
    post 'confirm'
    get 'thanks'
    end
  end
  end

   scope module: :public do
    root to: 'homes#top'
    # get 'homes/top'
    get 'homes/about'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :customers
    def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  enum response_status: { true: 0, false: 1 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price*amount
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :cart_items
   has_many :addresses
   has_many :orders, dependent: :destroy
   has_many :customers
  # def active_for_authentication?
  #   super && (is_valid == true)
  # end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_products
  def with_tax_price
    (price * 1.1).floor
  end
 has_one_attached :image
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end
  enum status: {
    on_sale:  0,   # 販売中
    sold_out: 1,   # 売り切れ
  }
end

app/models/order.rb
class Order < ApplicationRecord
  enum method_of_payment: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, make: 2, preparing: 3, shipped: 4 }
  # 0: 入金待ち, 1:入金確認, 2: 製作中, 3: 発送準備中, 4: 発送済み
  belongs_to :customer
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_started: 0, waiting: 1, make: 2, completion: 3 }
  # 0: 着手不可, 1:制作待ち, 2: 製作中, 3: 制作完了
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
    @ordes = Order.all
  end
  def show
    @customer = Customer.find(params[:id])
  end


  def edit
  end

  def update
  end
  private
  def customer_params
     params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end


  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  # Genre.find(params[:id]).update(genres_params)

  end
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    # @order_products = @orders.order_products
  end
  def order_params
   params.require(:order).permit(:shipping_name, :postage,:status, :created_at)
  end
  def order_product_params
    params.require(:order_product).permit(:quantity)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @item = Item.find(params[:id])
    @items = Item.page(params[:page]).per(3)
    @item = Item.all
    @genres = Genre.all

  end

  def new
    @item = Item.new
    @genres = Genre.all

  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
   params.require(:item).permit(:name, :introduction,:genre_id, :price, :image, :is_active)
  end
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end
  def order_params
   params.require(:order).permit(:shipping_postal_code, :shipping_address,:shipping_name, :method_of_payment, :postage, :billing_amount)
  end
  def order_product_params
    params.require(:order_product).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource_or_scope)
     if resource_or_scope == :customer
        root_path
     elsif resource_or_scope == :admin
        new_admin_session_path
     end
  end
   protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys: %i(email last_name first_name last_name_kana first_name_kana postal_code address telephone_number))
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>
<%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

  <h4>会員ID</h4>
  <%= @customer.id %>
  <h4>氏名</h4>
  <%= f.text_field :last_name %> <%= f.text_field :first_name %>
  <h4>フリガナ</h4>
  <%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %>
  <h4>郵便番号</h4>
  <%= f.text_field :postal_code %>
  <h4>住所</h4>
  <%= f.text_field :address %>
  <h4>電話番号</h4>
  <%= f.text_field :telephone_number %>
  <h4>メールアドレス</h4>
  <%= f.text_field :email %>

  <h4>会員ステータス</h4>
   <%= f.radio_button :is_deleted, true %>有効
  <%= f.radio_button :is_deleted, false %>退会

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>
<table class="table table-hover table-inverse">
  <thead>
              <div class="form-group">
                <th>会員ID</th>
              </div>
              <div class="form-group">
                <th>氏名</th>
              </div>

              <div class="form-group">
                <th>メールアドレス</th>
              </div>
              <div class="form-group">

                <th>ステータス</th>
              </div>
            </tr>
               <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td><%= link_to admin_customer_path(customer) do %>
                    <%= customer.last_name %><%= customer.first_name %>
                    <% end %></td>
                <td><%= customer.email %></td>
                <td>
                  <% if customer.is_deleted %>
                   無効
                  <% else %>
                  有効
                  <% end %></td>
              </tr>
               <% end %>

               </thead>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>
<h4>会員ID</h4>
<P><%= @customer.id %></P>
<h4>氏名</h4>
<P><%= @customer.last_name %> <%= @customer.first_name %></P>
<h4>フリガナ</h4>
<P><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></P>
<h4>郵便番号</h4>
<P><%= @customer.postal_code %></P>
<h4>住所</h4>
<P><%= @customer.address %></P>
<h4>電話番号</h4>
<P><%= @customer.telephone_number %></P>
<h4>メールアドレス</h4>
<P><%= @customer.email %></P>
<h4>会員ステータス</h4>
<P><%= @customer.is_deleted %></P>

<%= link_to '編集する',  edit_admin_customer_path(@customer) %>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>