config/routes.rb
Rails.application.routes.draw do


  # devise_for :customers
  # devise_for :admins

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# devise_for :admin, controllers: {
#   sessions: "admin/sessions"
# }
  # devise_for :customers
  namespace :admin do
    get 'order_products/updete'
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new'
     resources :items
    root to: 'homes#top'
    get 'homes/top'
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    resources :shipping_addresses

    resources :items, only: [:index, :show]

    resource :customers, except:[:create] do
    collection do
    get 'quit'
    patch 'out'
    end
    end
  end
    devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
    sessions: 'public/sessions'
}
  scope module: :public do
  resources :cart_items do
    collection do
    delete 'destroy_all'
    end
  end
  end
  scope module: :public do
  resources :orders do
    collection do
    post 'confirm'
    get 'thanks'
    end
  end
  end

   scope module: :public do
    root to: 'homes#top'
    # get 'homes/top'
    get 'homes/about'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :customers
    def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  enum response_status: { true: 0, false: 1 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price*amount
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :cart_items
   has_many :addresses
   has_many :orders, dependent: :destroy
   has_many :customers
  # def active_for_authentication?
  #   super && (is_valid == true)
  # end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_products
  def with_tax_price
    (price * 1.1).floor
  end
 has_one_attached :image
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end
  enum status: {
    on_sale:  0,   # 販売中
    sold_out: 1,   # 売り切れ
  }
end

app/models/order.rb
class Order < ApplicationRecord
  enum method_of_payment: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, make: 2, preparing: 3, shipped: 4 }
  # 0: 入金待ち, 1:入金確認, 2: 製作中, 3: 発送準備中, 4: 発送済み
  belongs_to :customer
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_started: 0, waiting: 1, make: 2, completion: 3 }
  # 0: 着手不可, 1:制作待ち, 2: 製作中, 3: 制作完了
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end


  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  # Genre.find(params[:id]).update(genres_params)

  end
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    # @order_products = @orders.order_products
  end
  def order_params
   params.require(:order).permit(:shipping_name, :postage,:status, :created_at)
  end
  def order_product_params
    params.require(:order_product).permit(:quantity)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @item = Item.find(params[:id])
    @items = Item.page(params[:page]).per(3)
    @item = Item.all
    @genres = Genre.all

  end

  def new
    @item = Item.new
    @genres = Genre.all

  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
   params.require(:item).permit(:name, :introduction,:genre_id, :price, :image, :is_active)
  end
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end
  def order_params
   params.require(:order).permit(:shipping_postal_code, :shipping_address,:shipping_name, :method_of_payment, :postage, :billing_amount)
  end
  def order_product_params
    params.require(:order_product).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource_or_scope)
     if resource_or_scope == :customer
        root_path
     elsif resource_or_scope == :admin
        new_admin_session_path
     end
  end
   protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys: %i(email last_name first_name last_name_kana first_name_kana postal_code address telephone_number))
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_products_helper.rb
module Admin::OrderProductsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch do |f| %>
<h4>ジャンル名</h4>
 <%= f.text_field :name %>

 <%= f.submit '変更を保存' %>
 <% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>
<%= form_with model: @genre, url: admin_genres_path do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit '新規登録' %>
<% end %>
<h4>ジャンル</h4>
<% @genres.each do |genre| %>


  <span><%= genre.name %></span>
<%= link_to '編集する', edit_admin_genre_path(genre) %><br>
<% end %>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>


  <h4>商品画像</h4>
  <%= f.file_field :image %>

  <h4>商品名</h4>
  <%= f.text_field :name %>

  <h4>商品説明</h4>
  <%= f.text_area :introduction %>

  <h4>ジャンル</h4>
  <%= f.collection_select :genre_id, @genres, :id, :name %>

  <h4>税抜価格</h4>
  <%= f.text_field :price %>円

  <h4>販売ステータス</h4>
  <%= f.radio_button :is_active, true %>販売中
  <%= f.radio_button :is_active, false %>販売停止中



  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/items/index.html.erb
<div class="col-md-8 offset-md-1">
       <h2>商品一覧</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
                <th></th>
              <div class="form-group">
                <th>商品ID</th>
              </div>
              <div class="form-group">
                <th>商品名</th>
              </div>
              <div class="form-group">
                <th>税抜価格</th>
              </div>
              <div class="form-group">
                <th>ジャンル</th>
              </div>
              <div class="form-group">
                <th colspan="3"></th>
              </div>
              <div class="form-group">
                <th>ステータス</th>
              </div>
            </tr>
    <% @items.each do |item| %>
    <tr>
      <td>
      </td>
    <td>
      <%= item.id %>
    </td>
        <td>
      <%= link_to item.name, admin_item_path(item) %>
        </td>
          <td>
            <%= item.price %>
          </td>
            <td>
              <%= item.genre.name %>
            </td>
              <div class="form-group">
                  <th colspan="3"></th>
              </div>
              <td>
                <% if item.is_active %>
                 販売中
                <% else %>
                販売停止中
                <% end %>
              </td>
       </tr>
      <% end %>
    <%= paginate @items %>
<%= link_to "新規登録", admin_items_new_path %>
</thead>
</table>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model: Item.new, url: admin_items_path do |f| %>

  <h4>商品画像</h4>
  <%= f.file_field :image %>

  <h4>商品名</h4>
  <%= f.text_field :name %>

  <h4>商品説明</h4>
  <%= f.text_area :introduction %>

  <h4>ジャンル</h4>
  <%= f.collection_select :genre_id, @genres, :id, :name %>

  <h4>税抜価格</h4>
  <%= f.text_field :price %>円

  <h4>販売ステータス</h4>
  <%= f.radio_button :is_active, true %>販売中
  <%= f.radio_button :is_active, false %>販売停止中



  <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
 <%= image_tag @item.get_image(300,300) %>
<h2>商品名</h2>
<p><%= @item.name %></p>

<h2>商品紹介</h2>
<p><%= @item.introduction %></p>
<h2>ジャンル</h2>
<p><%= @item.genre.name %></p>
<h2>税込価格<br>(税抜価格)</h2>
<p><%= @item.price %></p>
<h2>販売ステータス</h2>
<p><% if @item.is_active %>
 販売中
<% else %>
販売停止中
<% end %>
</p>
<%= link_to '編集する', edit_admin_item_path %>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<h4>注文履歴の詳細</h4>
<h2>購入者</h2>
<p><%= @order.shipping_name %></p>

<h2>注文日</h2>
<p><%= @order.created_at %></p>
<h2>配送先</h2>
<p><%= @order.shipping_address %></p>
<h2>支払方法<br>(税抜価格)</h2>
<p><%= @order.method_of_payment_i18n %></p>
<h2>注文ステータス</h2>
<%= form_with model: @order, url: orders_path(@order.id), method: :patch do |f| %>
<%= f.select :is_active, ['入金待ち', '入金確認', '制作中', '発送準備中', '発送済み'], {include_blank: '選択ボックス'},
class: 'sample' %>
<%= f.submit '更新' %>

<% end %>
 <table class="table table-bordered">
          <thead>
        <thead>
          <tr>
        <div class="form-group">
        <th>商品名</th>
        </div>
        <div class="form-group">
        <th>単価（税込）</th>
        </div>
        <div class="form-group">
        <th>数量</th>
        </div>
        <div class="form-group">
        <th>小計</th>
        </div>
        <div class="form-group">
        <th>製作ステータス</th>
        </div>
        </tr>
        </thead>
        <tbody>
         <% @order_products.each do |order_product| %>
         <%= form_with model: @order, url: orders_path(@order.id), method: :patch do |f| %>
          <tr>
          <td><%= order_product.item.name %></td>
          <td><%= order_product.tax_included_price %></td>
          <td><%= order_product.quantity %></td>
          <td><%= order_product.tax_included_price*order_product.quantity %></td>
          <!--<td><%= order_product.making_status %>< f.select :making_status, ['着手不可', '制作待ち', '制作中', '制作完了']　%></td>-->
          <td><%= f.submit '更新' %></td>
          </tr>
          </thead>
          </tsble>
         </tbody>
         <% end %>
         <% end %>
         <tr>
         <td>商品合計</td>
         <td><%= @order.billing_amount %>円</td>
         </tr>
         <tr>
         <td>送料</td>
         <td><%= @order.postage %>円</td>
         </tr>
         <tr>
         <td>請求金額合計</td>
         <td><%= @order.billing_amount + @order.postage %>円</td>
         </tr>