config/routes.rb
Rails.application.routes.draw do


  # devise_for :customers
  # devise_for :admins

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# devise_for :admin, controllers: {
#   sessions: "admin/sessions"
# }
  # devise_for :customers
  namespace :admin do
    get 'order_products/updete'
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new'
     resources :items
    root to: 'homes#top'
    get 'homes/top'
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    resources :shipping_addresses

    resources :items, only: [:index, :show]

    resource :customers, except:[:create] do
    collection do
    get 'quit'
    patch 'out'
    end
    end
  end
    devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
    sessions: 'public/sessions'
}
  scope module: :public do
  resources :cart_items do
    collection do
    delete 'destroy_all'
    end
  end
  end
  scope module: :public do
  resources :orders do
    collection do
    post 'confirm'
    get 'thanks'
    end
  end
  end

   scope module: :public do
    root to: 'homes#top'
    # get 'homes/top'
    get 'homes/about'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :customers
    def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  enum response_status: { true: 0, false: 1 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price*amount
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :cart_items
   has_many :addresses
   has_many :orders, dependent: :destroy
   has_many :customers
  # def active_for_authentication?
  #   super && (is_valid == true)
  # end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_products
  def with_tax_price
    (price * 1.1).floor
  end
 has_one_attached :image
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end
  enum status: {
    on_sale:  0,   # 販売中
    sold_out: 1,   # 売り切れ
  }
end

app/models/order.rb
class Order < ApplicationRecord
  enum method_of_payment: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, make: 2, preparing: 3, shipped: 4 }
  # 0: 入金待ち, 1:入金確認, 2: 製作中, 3: 発送準備中, 4: 発送済み
  belongs_to :customer
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { not_started: 0, waiting: 1, make: 2, completion: 3 }
  # 0: 着手不可, 1:制作待ち, 2: 製作中, 3: 制作完了
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    # @order_products = @orders.order_products
  end
  def order_params
   params.require(:order).permit(:shipping_name, :postage,:status, :created_at)
  end
  def order_product_params
    params.require(:order_product).permit(:quantity)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @item = Item.find(params[:id])
    @items = Item.page(params[:page]).per(3)
    @item = Item.all
    @genres = Genre.all

  end

  def new
    @item = Item.new
    @genres = Genre.all

  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
   params.require(:item).permit(:name, :introduction,:genre_id, :price, :image, :is_active)
  end
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource_or_scope)
     if resource_or_scope == :customer
        root_path
     elsif resource_or_scope == :admin
        new_admin_session_path
     end
  end
   protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys: %i(email last_name first_name last_name_kana first_name_kana postal_code address telephone_number))
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_admin_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <script src="https://kit.fontawesome.com/eb6f9385ef.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if admin_signed_in? %>
             <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "ながのcake", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">

        <li class="nav-item">
            <%= link_to admin_items_path, class:"nav-link text-dark" do  %>
            商品一覧
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to admin_customers_path, class:"nav-link text-dark" do  %>
            会員一覧
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to admin_root_path, class:"nav-link text-dark" do  %>
            注文履歴一覧
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to admin_root_path, class:"nav-link text-dark" do  %>
            ジャンル一覧
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-dark" do  %>
            ログアウト
            <% end %>
        </li>
        </ul>
        </nav>
        <% elsif customer_signed_in? %>
       <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "ながのcake", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to customers_path, class:"nav-link text-dark" do  %>
            マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class:"nav-link text-dark" do  %>
            商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to orders_path, class:"nav-link text-dark" do  %>
            注文履歴一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to  cart_items_path, class:"nav-link text-dark" do  %>
            カート
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link text-dark" do  %>
            ログアウト
            <% end %>
         </li>
          </ul>
         </nav>
      <% else %>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "ながのcake", root_path, class: "navbar-brand" %>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

      <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">

        <li class="nav-item">
            <%= link_to homes_about_path, class:"nav-link text-dark" do  %>
            About
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to items_path, class:"nav-link text-dark" do  %>
            商品一覧
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to new_customer_registration_path, class:"nav-link text-dark" do  %>
            新規登録
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to customer_session_path, class:"nav-link text-dark" do  %>
            ログイン
            <% end %>
        </li>
         </ul>
       <% end %>
    </header>
    </nav>
    <%= yield %>

    </div>
    </div>
    </div>
    </div>
    </div>

  </body>
</html>